name: hydit
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - cuda-toolkit==12.1
  - ninja
  - pip:
      - packaging
      - numpy<2
      - black
      - isort
      - pre-commit
      - flake8
      - flake8-bugbear==24.2.6
      - flake8-comprehensions
      - flake8-simplify
